# Generated by Django 4.0 on 2024-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_text_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rented', 'Rented'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('damaged', 'Damaged')], default='pending', max_length=10),
        ),
    ]
