# Generated by Django 4.0 on 2024-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_product_quantity_remove_rent_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('none', 'None'), ('sofa', 'Sofa'), ('chair', 'Chair'), ('table', 'Table'), ('bed', 'Bed')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
