# Generated by Django 5.0.3 on 2024-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_sofa', models.IntegerField(default=4)),
                ('threshold_chair', models.IntegerField(default=4)),
                ('threshold_table', models.IntegerField(default=4)),
                ('threshold_bed', models.IntegerField(default=4)),
                ('available_sofa', models.IntegerField(default=0)),
                ('available_chair', models.IntegerField(default=0)),
                ('available_table', models.IntegerField(default=0)),
                ('available_bed', models.IntegerField(default=0)),
            ],
        ),
    ]
