# Generated by Django 5.0.3 on 2024-03-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='available_bed',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='available_chair',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='available_sofa',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='available_table',
            field=models.IntegerField(default=4),
        ),
    ]
