# Generated by Django 5.0.3 on 2024-04-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_notifications_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='available_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='available_chair',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='available_sofa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='available_table',
            field=models.IntegerField(default=0),
        ),
    ]
